### ISSUE TITLE
Allow choosing decks when generating mobile cards.

### ISSUE THREAD

**Issue by aleksejrs** [kelciour/movies2anki#8] opened 2019-01-16 19:54 UTC
I actually want to split small videos into pieces to use in ordinary cards, so I don't need to split a big TV series episode at the time (which also wouldn't work on my smartphone).

Using a search query would be even more useful, for using a separate card to configure that.

Maybe you know a program that could do that on GNU/Linux?

**Comment by kelciour** [comment] 2019-01-16 20:28
Right now the only way is to export a deck as apkg file and use a different [Anki profile](https://apps.ankiweb.net/docs/manual.html#profiles-&-preferences) to generate mobile cards.

> Using a search query would be even more useful, for using a separate card to configure that.
> 
> Maybe you know a program that could do that on GNU/Linux?

I'm sorry, but I don't understand it. What do you mean by that?

**Comment by aleksejrs** [comment] 2019-01-16 21:13
> Right now the only way is to export a deck as apkg file and use a different [Anki profile](https://apps.ankiweb.net/docs/manual.html#profiles-&-preferences) to generate mobile cards.

Well, that would work, too, for now; thank you.

> > Using a search query would be even more useful, for using a separate card to configure that.
> > Maybe you know a program that could do that on GNU/Linux?
> 
> I'm sorry, but I don't understand it. What do you mean by that?

1. Choosing the cards to generate separate files for using a filter query (like in the Browser or a filtered deck).
2. A program to make it easier to split a video into video and audio pieces using subtitles outside of Anki. Maybe an audio or video editor that would mark subtitled pieces and make it easy to select them and export them as audio with convenient names based on the file name and the subtitle text (that would make it easy to choose pieces of the text to use separate words).  Audacity does not support subtitle formats for its labels and apparently will not.

**Comment by kelciour** [comment] 2019-01-16 21:39
> Choosing the cards to generate separate files for using a filter query (like in the Browser or a filtered deck).

Generate mobile cards for selected cards in the browser? Something similar to [Localize Media](https://ankiweb.net/shared/info/1293255374) add-on? Yeah, sure, something like this can be added in the future.

> A program to make it easier to split a video into video and audio pieces using subtitles outside of Anki.

Why not to do it in Anki using movies2anki add-on? :) And some part of [subs2srs preview window](http://subs2srs.sourceforge.net/#preview) can be imitated by using movies2anki add-on and Anki cards browser.
Or maybe use Aegisub to preview and correct subtitle timings and subs2srs or movies2anki standalone app to export cards as video and audio.
And as an alternative, maybe mpv video player with [sub-cut.lua](https://github.com/kelciour/mpv-scripts/blob/master/sub-cut.lua) to export a part of a video as audio or video and maybe [sub-search.lua](https://github.com/kelciour/mpv-scripts/blob/master/sub-search.lua) to search for specific english words in subtitles.

**Comment by kelciour** [comment] 2024-04-21 21:21
The issue is too old and aside from selectively generate cards from the browser, there's nothing much I can do. I'll close it and create a new issue for it.

https://github.com/kelciour/movies2anki/issues/32

If it's fixed, it can be combined with https://ankiweb.net/shared/info/567329012 ("Media Exporter") to export media from selected notes to a specific folder.

**Closed as completed by kelciour** 2024-04-21 21:21 UTC
